ARG BASE=nvidia/cuda:10.2-devel
FROM $BASE

ARG ADDITIONAL_PACKAGES

RUN apt-get update && apt-get install -y \
    bc \
    git \
    wget \
    ccache \
    python3 \
    python3-pip \
    $ADDITIONAL_PACKAGES \
    && \
    apt-get --purge autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m pip install 'cmake==3.18.4'
